# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PointAndLineToPlane' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PointAndLineToPlane

pod 'KakaoSDK'

  # Pods for kakaoTestApp

  target 'kakaoTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kakaoTestAppUITests' do
    # Pods for testing
  end

end
